# Generated by Django 5.2.9 on 2025-12-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complaint',
            table='complaints',
        ),
    ]
