# Generated by Django 5.2.9 on 2025-12-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In Progress', 'in progress'), ('Resolved', 'resolved')], default='Pending'),
        ),
    ]
