# Generated by Django 5.2.9 on 2025-12-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaint_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='user_id',
        ),
    ]
