# Generated by Django 5.2.9 on 2025-12-31 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_rename_user_complaint_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user_id',
            new_name='user',
        ),
    ]
